### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by mjjs** [otahontas/exact-cover-solver#1]
# Vertaisarvio 1
Arvioitu commit: b9008a267846d3f13a90f4b939dcf99f35840515

Ladattu: 25.11.2020

## Poetryn käyttö
En saanut poetryllä jostain syystä mitään antamiasi komentoja toimimaan, vaan sain aina vastaukseksi:

```
OSError

[Errno 2] No such file or directory
```

Sain koodin sekä testit kuitenkin ajettua käyttämällä python3/pypy3/pytestiä.

## Testaus
Testikattavuus näyttää olevan hyvällä mallilla. Joitain osia sieltä täältä ei oltu testattu, mutta tärkeimmät, eli algoritmit sekä tietorakenteet, olivat lähes sadassa prosentissa. Testit näyttävät myös olevan järkevästi kirjoitettu ja ne testaavat oikeita asioita.

## Koodi
Koodista huomaa, ettet ole ihan ensimmäistä kertaa ohjelmoimassa. Eri toiminnallisuudet on jaettu järkeviin kokonaisuuksiin omiin moduuleihinsa, mikä tekee koodin löytämisestä helppoa vaikkei projekti olisi ennalta tuttu. Myös Pythonin eri ominaisuuksia, joita aloittelija ei välttämättä keksisi käyttää, on käytetty kattavasti. Näistä esimerkkejä ovat mm. tyyppivinkit, testien fixturet sekä muut decoratorit. Myös projektin readme on toteutettu hyvin.

### Ehdotuksia

Ensimmäinen "ongelma", mikä pisti silmään lähes jokaisessa tiedostossa, on koodin pötköisyys. Mielestäni koodia on vaikea lukea, kun kaikki rivit ovat kiinni toisissaan. Jos verrataan esimerkiksi seuraavaa koodipätkää tiedostosta `dlxmatrix.py`
```python
for set_number, set_elements in enumerate(self._set_collection):
    previous = None
    first = None
    for element in set_elements:
        column = find_column(element)
        cell = DataObject(column, row=set_number)
        prev_up = column.up
        prev_up.down = cell
        cell.up = prev_up
        cell.down = column
        column.up = cell
        if previous:
            previous.right = cell
            cell.left = previous
        else:
            first = cell
        previous = cell
        column.size += 1
    previous.right = first
    first.left = previous
```
ja samaa koodipätkää hieman jäsenneltynä
```python
for set_number, set_elements in enumerate(self._set_collection):
    previous = None
    first = None

    for element in set_elements:
        column = find_column(element)
        cell = DataObject(column, row=set_number)

        prev_up = column.up
        prev_up.down = cell

        cell.up = prev_up
        cell.down = column
        column.up = cell

        if previous:
            previous.right = cell
            cell.left = previous
        else:
            first = cell

        previous = cell
        column.size += 1

    previous.right = first
    first.left = previous
```
niin huomataan, että jälkimmäinen on (ainakin minun mielestäni) helpompi lukea.

Vaikka käyttöliittymä ei olekaan tämän kurssin keskiössä, mainitsen käyttöliittymäkoodistasi yhden ongelman joka tuli vastaan.
Olet käyttänyt tiedostossa `exact_cover_solver/ui/__init__.py` metodin `_update_view` parametreissä nimeä `next`, mikä yliajaa Pythonin sisäänrakennetun funktion `next`. Vaikka tämä ei olekaan ongelma tässä tilanteessa, ei kielen sisäänrakennettujen avainsanojen yliajaminen (yleensä) ole järkevää, ja se saattaa johtaa bugeihin.

Mitään tämän suurempia ongelmia en koodista löytänyt, eikä minulla valitettavasti ole ollut tällä viikolla aikaa hirveästi tähän paneutua. Projekti näyttää olevan sinun osaltasi kuitenkin jo hyvällä mallilla.

**Comment by otahontas** [comment]
Kiitokset palautteesta! Harmi, ettei poetry lähtenyt toimimaan. Kokeilin kyllä pyöräyttää projektin yliopiston koneilla ja hyvin se toimi, joten en oikein osaa sanoa, mistä tämä olisi johtunut. 

Hyviä bongauksia koodista, fiksailin niitä.
