### ISSUE TITLE
Vertaisarvio

### ISSUE THREAD

**Issue by Qwecu** [otahontas/exact-cover-solver#2]
-Todella mielenkiintoinen ongelma ja algoritmi, tuli vietettyä hetki jos toinenkin Wikipediassa ja Youtubessa tutustumassa tämän sovelluksiin.

-Testikattavuus & koodin laadun seuranta näkyvissä suoraan Githubissa, erittäin kätevää

-koodin selkeys ja kommentointi esimerkillistä

-nimeäminen hyvin selkeää, erityisesti testien nimeämisestä pitää itsekin ottaa mallia

-En saanut ikävä kyllä ohjelmaa ajettua käyttöohjeiden perusteella ilman kokemusta Pythonista :( 

-En saanut ohjelmaa ajettua Windowsilla: asensin Pythonin ja Pypyn, mutta ohjeissa jumahdin kohtaan 'source' is not recognized as an internal or external command,operable program or batch file.

-En saanut ohjelmaa ajettua Debianilla, sopivan Python-version asentaminen ei onnistunut tässä ajassa

-Ubuntulla onnistui siihen asti, että kosahti XWindow:n puuttumiseen. Tämä onnistui freesissä virtuaalikoneessa seuraavasti:

sudo apt upgrade && sudo apt update
sudo apt install python3
sudo apt install pypy3
sudo apt install python3-pip
git clone https://github.com/otahontas/exact-cover-solver
cd exact-cover-solver/
pypy3 -m venv venv
source venv/bin/activate
pypy3 -m pip install --upgrade pip
pypy3 -m pip install .
pypy3 exact_cover_solver/main.py
sudo apt-get install python3-tk
sudo apt install pypy3-tk
pypy3 exact_cover_solver/main.py

Käyttöohjeet voisivat tältä osin kaivata vähän täydennystä, että kokemattomammaltakin onnistuisi.

Harmi etten päässyt ohjelmaa kokeilemaan, mutta repon perusteella epäilen kyllä lukeneeni jotain "näin saat arvosanan 6" -malliprojektia enkä vertaisarvioitavaa repoa :)

**Comment by otahontas** [comment]
Kiitos mukavasta palautteesta! 

Ja harmi homma, ettei ohjelma lähtenyt pyörimään. En ole käyttänyt Windowsia koodaamiseen, mutta selvästi olisi pitänyt dual boottailla Windowsin puolelle ja testata ohjeet. Tuossa virtuaalikoneessa (oletan, että käytössä oli Windows Subsystem for Linux) pyörittäminen vaatii tosiaankin varmaan jotain extrapaketteja, en ollut tullut ajatelleeksi asiaa. Hyvä siis, että testasit :)
